# Generated by Django 2.0.5 on 2019-04-15 14:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('binty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 14, 45, 15, 556894, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='content',
            name='cast',
            field=models.ManyToManyField(blank=True, null=True, to='binty.Cast', verbose_name='キャスト'),
        ),
        migrations.AlterField(
            model_name='content',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='binty.Director', verbose_name='監督'),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='binty.Genre', verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 14, 45, 15, 557520, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='director',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 14, 45, 15, 556521, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='genre',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 14, 45, 15, 556196, tzinfo=utc)),
        ),
    ]
